name: Buildroot
on: [push]

jobs:
  matrix_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Buildroot sources
        run: git clone --depth=1 --branch=2020.11.1 https://git.busybox.net/buildroot
