name: Buildroot
on: [push]

jobs:
  matrix_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        defconfig_name: [qemu_x86_defconfig, qemu_x86_64_defconfig]
    steps:
      - name: Checkout Buildroot sources
        run: git clone --depth=1 --branch=2020.11.1 https://git.busybox.net/buildroot
      - name: Select latest PPP version
        working-directory: buildroot/package/pppd
        run: |
          # Allow package to build when musl libc is selected
          sed -i '/depends on !BR2_TOOLCHAIN_USES_MUSL/d' Config.in
          # Do not check for package hash, so there is no need to compute it
          rm pppd.hash
          # Get package sources from head of master branch
          sed -i '/PPPD_VERSION =/c\\PPPD_VERSION = master' pppd.mk
          sed -i '/PPPD_SITE =/c\\PPPD_SITE = https://github.com/paulusmack/ppp' pppd.mk
          sed -i '9iPPPD_MUSL_SITE_METHOD = git' pppd.mk
      - name: Enable PPP build
        working-directory: buildroot
        run: |
          echo "BR2_PACKAGE_PPPD=y" >> configs/${{ matrix.defconfig_name }}
          # TODO enable other PPP package options if needed
          cat configs/${{ matrix.defconfig_name }}
